### ISSUE TITLE
[Feature] Integrate the Submit endpoint with QCEngine

### ISSUE THREAD

**Issue by mohsenbakhit** [UBCC3/cluster-api#10]
### Description
As the cluster receives the submit call, it takes the job request, makes the SBATCH file with the correct parameters and then QCEngine runs the appropriate calculations.
The results are then returned to the client.

### Implementation Plan
- Add in the parameters in the job dictionary to the submit_job.sh script.
- Add input parameters to the QCEngine file.
- Have QCEngine product output in form of a file or stdout.

### Definition of Done
- [ ] Feature has been implemented and tested.
- [ ] Code changes have been reviewed and approved.
- [ ] Documentation has been updated to reflect the new feature.
- [ ] Feature has been deployed to the staging environment.
- [ ] Feature has been tested in the staging environment.
